### ISSUE TITLE
Supports SVG?

### ISSUE THREAD

**Issue by duopixel** [dosyago-coder-0/brutal.js#18]
I made a little experiment with SVG and nothing rendered. Is SVG supported?

**Comment by duopixel** [comment]
I just made a jsfiddle and it rendered: http://jsfiddle.net/4euj8g9z/1/ so something must have been wrong with my initial experiment. I'll give it a spin and if I feel confident I might even PR! Thanks for your help.

**Comment by dosyago-coder-0** [comment]
Thank you ! :)

But there are sometimes some strange non-intuitive bugs. I'm working to get
rid of these. A significant update removing some of these should be in 1.4

Appreciate your report
